ZilZolMarket/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ZilZolMarket.Models
{
     public class Product
    {
        public int Id { get; set; }

        [DisplayName("Product Type")]
        public string ProductType { get; set; }

        public string Company { get; set; }

        public string Name { get; set; }

        public double Price { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Released")]
        public DateTime Date { get; set; }

        public int Quantity { get; set; }

        [DisplayName("Size Of Screen")]
        public double Size { get; set; }


        [Required]
        public string img { get; set; }

        public ICollection<ProductOrder> ProductsOrders { get; set; }

    }
}

ZilZolMarket/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZilZolMarket.Data;
using ZilZolMarket.Models;

namespace ZilZolMarket.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ZilZolMarketContext _context;

        public OrdersController(ZilZolMarketContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details()
        {
            int id = int.Parse(User.Claims.FirstOrDefault(x => x.Type.Equals("Id", StringComparison.OrdinalIgnoreCase))?.Value);
            User user = _context.User.Where(u => u.Id == id).ToList().First();
            List<Orders> ord = await _context.Orders.Where(o => o.User == user).ToListAsync();
            return View(ord);
        }

        // GET: Orders/Create
        public async Task<IActionResult> Create(Orders o)
        {
            var product = await _context.Product.ToListAsync();
            List<string> l;
            string cart = HttpContext.Session.GetString("cart");
            if (cart == null)
            {
                l = new List<string>();
            }
            else l = cart.Split(',').ToList();
            List<Product> lp = new List<Product>();
            string pro = "";
            for (int i = 0; i < l.Count; i += 6)
            {
                pro += l.ElementAt(i) + "," + l.ElementAt(i + 3);
                if (i+5 < l.Count - 1)
                    pro += ",";
            }
            o.DateOfOrder = DateTime.Now;
            string id = User.Claims.FirstOrDefault(x => x.Type.Equals("Id", StringComparison.OrdinalIgnoreCase))?.Value;
            int j = int.Parse(id);
            o.User = _context.User.Where(u => u.Id == j).ToList().First();
            _context.Add(o);
            await _context.SaveChangesAsync();
            return RedirectToAction("Create", "ProductOrders", new { prodc = pro });
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /*public async Task<IActionResult> Create([Bind("Id,DateOfOrder,TotalPrice")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }*/

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            return View(orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateOfOrder,TotalPrice")] Orders orders)
        {
            if (id != orders.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdersExists(orders.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orders = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(orders);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdersExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

ZilZolMarket/Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZilZolMarket.Data;
using ZilZolMarket.Models;

namespace ZilZolMarket.Controllers
{
    public class PhonesController : Controller
    {
        private readonly ZilZolMarketContext _context;

        public PhonesController(ZilZolMarketContext context)
        {
            _context = context;
        }

        // GET: Phones
        public async Task<IActionResult> Index()
        {
            return View(await _context.Phone.ToListAsync());
        }

        public async Task<IActionResult> Search(string name, double price)
        {
            IQueryable<Phone> phones = _context.Phone;

            if (!string.IsNullOrEmpty(name))
                phones = phones.Where(p => p.Name.Contains(name) || p.Company.Contains(name));

            if (price > 0)
                phones = phones.Where(p => p.Price < price);

            return View("Index", await phones.ToListAsync());
        }

        // GET: Phones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // GET: Phones/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Phones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Weight,Id,ProductType,Company,Name,Price,Date,Quantity,Size,img")] Phone phone)
        {
            phone.ProductType = "Phone";
            if (ModelState.IsValid)
            {
                _context.Add(phone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(phone);
        }

        // GET: Phones/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone.FindAsync(id);
            if (phone == null)
            {
                return NotFound();
            }
            return View(phone);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Weight,Id,ProductType,Company,Name,Price,Date,Quantity,Size")] Phone phone)
        {
            if (id != phone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneExists(phone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phone);
        }

        // GET: Phones/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var phone = await _context.Phone.FindAsync(id);
            _context.Phone.Remove(phone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneExists(int id)
        {
            return _context.Phone.Any(e => e.Id == id);
        }
    }
}

ZilZolMarket/Views/Products/Cart.cshtml
@model ZilZolMarket.Models.Orders
@{
    ViewData["Title"] = "Cart";

}


<!-- slider Area Start-->
<div class="slider-area ">
    <!-- Mobile Menu -->
    <div class="single-slider slider-height2 d-flex align-items-center" data-background="assets/img/hero/category.jpg">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Cart</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider Area End-->
<!--================Cart Area =================-->
<section class="cart_area section_padding">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            double sum = 0;
                            List<Product> lp = (List<Product>)ViewData["products"];
                            foreach (Product p in lp)
                            {
                                sum += p.Price;
                                <tr>
                                    <td>
                                        <div class="media">
                                            <div class="d-flex">
                                                <img src="@p.img.ToString()" alt="" />
                                            </div>
                                            <div class="media-body">
                                                <p>@p.Company @p.Name</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <h5>@{double pr = p.Price / p.Quantity;} @pr$</h5>
                                    </td>
                                    <td>
                                        <h5>@p.Quantity</h5>
                                    </td>
                                    <td>
                                        <h5>@p.Price$</h5>
                                    </td>
                                </tr>
                                            }
                        }
                    <tr>
                        <td></td>
                        <td></td>
                        @{ if (lp.Count != 0)
                            {
                                <td>
                                    <h5>Total sum of cart</h5>
                                </td>
                                <td>
                                    <h5>@sum$</h5>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <h5>Cart is empty</h5>
                                </td>
                            }
                        }
                    </tr>
                    </tbody>
                </table>
                @{ if (lp.Count!=0)
                    {
                <form asp-action="Create" asp-controller="Orders" asp-route-TotalPrice="@sum">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-12 form-group p_star">
                        <input asp-for="Address" class="form-control" placeholder="Address" required pattern="{4,16}" title="Length must be 4 to 16 chars" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="col-md-12 form-group p_star">
                        <input asp-for="City" class="form-control" placeholder="City" required pattern="{4,16}" title="Length must be 4 to 16 chars" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="col-md-12 form-group p_star">
                        <input asp-for="Zip" class="form-control" placeholder="Zip Code" required pattern="[0-9]{7}" title="Zip Code must have 7 digits only" />
                        <span asp-validation-for="Zip" class="text-danger"></span>
                    </div>
                    <div class="raw">
                        <div class="col-md-12 form-group p_star">
                            <input class="form-control" id="credit" placeholder="Credit Card" required pattern="[0-9]{16}" title="Credit Card must have 16 digits only" oninput="check()" maxlength="16">
                        </div>
                        <div class="col-md-12 form-group p_star">
                            <input class="form-control" placeholder="CVV" required pattern="[0-9]{3}" title="CVV must have 3 digits only">
                        </div>
                        @{
                            int month = DateTime.Now.Month;
                            int year = DateTime.Now.Year;
                            if (month == 12)
                            {
                                year++;
                                month = 1;
                            }

                            else
                            {
                                month++;
                            }
                        }
                        <div class="col-md-12 form-group p_star">
                            <input type="month" id="start" name="start"
                                   min="@year.ToString()-@month.ToString()" required>
                        </div>
                        <script>
                            function check() {
                                var credit = document.getElementById("credit").value;
                                var c;
                                if (credit > 999999999999999) {
                                    c = credit % 10000;
                                    document.getElementById("cre").value = c;
                                }
                                   
                            }
                        </script>
                    </div>
                    <div class="col-md-12 form-group p_star">
                        <input asp-for="CreditCard" id="cre" class="form-control" hidden/>
                        <span asp-validation-for="CreditCard" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Checkout" class="btn_1 checkout_btn_1" />
                    </div>
                </form>
                                }
                            }
            </div>
        </div>
    </div>
</section>
<!--================End Cart Area =================-->

ZilZolMarket/Views/Products/Index.cshtml
@model IEnumerable<ZilZolMarket.Models.Product>

@{
    ViewData["Title"] = "Index";

}

<link type="text/css" rel="stylesheet" href="~/css/model1.css" />
<link rel="stylesheet" href="~/css/style1.css">


@{
    string time;
    int hour = DateTime.Now.Hour;
    if (hour >= 6 && hour < 12)
        time = "Good morning";
    else if (hour >= 12 && hour < 19)
        time = "Have a nice day";
    else
        time = "Good night";
}

<h2>@time, @ViewData["login"]</h2>

@{
    string user = ViewData["login"].ToString();
    if (user.Equals("guest"))
    {
        <h3>We recomend you to log in!</h3>
    }
    /*  else
      {
          <h3>jsfkfjhkjvhrkjhk</h3>
      }*/

}


    <!-- slider Area End-->
    <!-- Category Area Start-->
    <section class="category-area">
        <div class="container-fluid">
            <!-- Section Tittle -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-tittle text-center mb-85">
                        <h2>Welcome to ZilZol Market!</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-4 col-lg-6">
                    <div class="single-category mb-30">
                        <div class="category-img">
                            <a href="/Phones/Index">
                                <img src="~/img/Products/Phones.jpg" alt="">
                                <div class="category-caption">
                                    <h2>Phones</h2>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6">
                    <div class="single-category mb-30">
                        <div class="category-img">
                            <a href="/Pcs/Index">
                                <img src="/img/Products/PC.jpg" alt="" style="
                                     width: 472px;
                                     ">
                                <div class="category-caption">
                                    <h2>PC's</h2>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6">
                    <div class="single-category mb-30">
                        <div class="category-img">
                            <a href="/Screens/Index">
                                <img src="/img/Products/Screen.jpg" alt="" style="
                                    width: 396px;
                                    ">
                                <div class="category-caption"
                                     style="
                                     top: 289px;
                                     ">
                                    <h2>Screens</h2>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


<br />
<br />
<br />
<br />

<section class="latest-product-area padding-bottom">
        <div class="container">
            <div class="row product-btn d-flex justify-content-end align-items-end">
                <!-- Section Tittle -->
                <div class="col-xl-4 col-lg-5 col-md-5">
                    <div class="section-tittle mb-30">
                        <h2>Latest Products</h2>
                    </div>
                </div>
                <div class="col-xl-8 col-lg-7 col-md-7">
                    <div class="properties__button f-right">
                        <!--Nav Button  -->
                        <nav>
                 
                        </nav>
                        <!--End Nav Button  -->
                    </div>
                </div>
            </div>
            <!-- Nav Card -->
            <div class="tab-content" id="nav-tabContent">
                <div class="col-md-6">
                    <div class="product_list">
                        <div class="row">
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    if (item.Quantity <= 0)
                                        continue;

                                    if (item.ProductType == "Phone")
                                    {
                                      <div class="col-lg-6 col-sm-6">
                                        <div class="single_product_item">
                                            <a asp-controller="Phones" asp-action="Details" asp-route-id="@item.Id">
                                                <img src="@item.img.ToString()" class="img-fluid">
                                            </a>
                                            <h3>
                                                <a asp-controller="Phones" asp-action="Details" asp-route-id="@item.Id">
                                                    @item.Company  @item.Name

                                                </a>
                                            </h3>
                                            <p>@item.Price $</p>
                                                    @{ if (User.Identity.IsAuthenticated && User.Claims.ElementAt(3).Value == "Admin")
                                                        {
                                                        <p>
                                                            <a asp-action="Edit" asp-route-id="@item.Id" style="color:black">Edit</a> |
                                                            <a asp-action="Delete" asp-route-id="@item.Id" style="color:red">Delete</a>
                                                        </p> 
                                                        }
                                                }
                              
                                        </div>
                                      </div>
                                                        }

                                                        if (item.ProductType == "Pcs")
                                                        {
                                      <div class="col-lg-6 col-sm-6">
                                        <div class="single_product_item">
                                            <a asp-controller="Pcs" asp-action="Details" asp-route-id="@item.Id">
                                                <img src="@item.img.ToString()" class="img-fluid">
                                            </a>
                                            <h3>
                                                <a asp-controller="Pcs" asp-action="Details" asp-route-id="@item.Id">
                                                    @item.Company  @item.Name

                                                </a>
                                            </h3>
                                            <p>@item.Price $</p>
                                                  @{ if (User.Identity.IsAuthenticated && User.Claims.ElementAt(3).Value == "Admin")
                                                      {
                                                        <p>
                                                            <a asp-action="Edit" asp-route-id="@item.Id" style="color:black">Edit</a> |
                                                            <a asp-action="Delete" asp-route-id="@item.Id" style="color:red">Delete</a>
                                                        </p> 
                                                      }
                                                }
                              
                                        </div>
                                      </div>
                                                      }
                                                      if (item.ProductType == "Screens")
                                                      {
                                      <div class="col-lg-6 col-sm-6">
                                        <div class="single_product_item">
                                            <a asp-controller="Screens" asp-action="Details" asp-route-id="@item.Id">
                                                <img src="@item.img.ToString()" class="img-fluid">
                                            </a>
                                            <h3>
                                                <a asp-controller="Screens" asp-action="Details" asp-route-id="@item.Id">
                                                    @item.Company  @item.Name

                                                </a>
                                            </h3>
                                            <p>@item.Price $</p>
                                                    @{ if (User.Identity.IsAuthenticated && User.Claims.ElementAt(3).Value == "Admin")
                                                        {
                                                        <p>
                                                            <a asp-action="Edit" asp-route-id="@item.Id" style="color:black">Edit</a> |
                                                            <a asp-action="Delete" asp-route-id="@item.Id" style="color:red">Delete</a>
                                                        </p> 
                                                        }
                                                }
                              
                                        </div>
                                      </div>
                                                                }
                                                            }
                                                        }
                             </div>
                    </div>
                </div>
                <!-- End Nav Card -->
            </div>
    </section>



<div class="shop-method-area section-padding30">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-package"></i>
                        <h6>Free Shipping Method</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-unlock"></i>
                        <h6>Secure Payment System</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-reload"></i>
                        <h6>Secure Payment System</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
      

ZilZolMarket/Views/Products/Sales.cshtml
@model IEnumerable<ZilZolMarket.Models.GroupJoin>

@{
    ViewData["Title"] = "Sales";
}

<div class="row">

    <div class="col-4">

    </div>


    <div class="col-4">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        User Name
                    </th>
                    <th>
                        Total
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null ) {
                    foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalPrice)$
                        </td>
                    </tr>
                    }
                }
            </tbody>
        </table>


    </div>
</div>