ZilZolMarket/Controllers/PcsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZilZolMarket.Data;
using ZilZolMarket.Models;

namespace ZilZolMarket.Controllers
{
    public class PcsController : Controller
    {
        private readonly ZilZolMarketContext _context;

        public PcsController(ZilZolMarketContext context)
        {
            _context = context;
        }

        // GET: Pcs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pc.ToListAsync());
        }

        public async Task<IActionResult> Search(string name, double price)
        {
            IQueryable<Pc> pcs = _context.Pc;

            if (!string.IsNullOrEmpty(name))
                pcs = pcs.Where(p => p.Name.Contains(name) || p.Company.Contains(name));

            if (price > 0)
                pcs = pcs.Where(p => p.Price < price);

            return View("Index", await pcs.ToListAsync()); 
        }


        // GET: Pcs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pc = await _context.Pc
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pc == null)
            {
                return NotFound();
            }

            return View(pc);
        }

        // GET: Pcs/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pcs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cpu,Laptop,Ram,GraphicsCard,Storage,Id,ProductType,Company,Name,Price,Date,Quantity,Size,img")] Pc pc)
        {
            pc.ProductType = "PC";
            if (ModelState.IsValid)
            {
                _context.Add(pc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pc);
        }

        // GET: Pcs/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pc = await _context.Pc.FindAsync(id);
            if (pc == null)
            {
                return NotFound();
            }
            return View(pc);
        }

        // POST: Pcs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Cpu,Laptop,Ram,GraphicsCard,Storage,Id,ProductType,Company,Name,Price,Date,Quantity,Size,img")] Pc pc)
        {
            if (id != pc.Id)
            {
                return NotFound();
            }
            pc.ProductType = "PC";
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PcExists(pc.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pc);
        }

        // GET: Pcs/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pc = await _context.Pc
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pc == null)
            {
                return NotFound();
            }

            return View(pc);
        }

        // POST: Pcs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pc = await _context.Pc.FindAsync(id);
            _context.Pc.Remove(pc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PcExists(int id)
        {
            return _context.Pc.Any(e => e.Id == id);
        }
    }
}

ZilZolMarket/Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZilZolMarket.Data;
using ZilZolMarket.Models;

namespace ZilZolMarket.Controllers
{
    public class PhonesController : Controller
    {
        private readonly ZilZolMarketContext _context;

        public PhonesController(ZilZolMarketContext context)
        {
            _context = context;
        }

        // GET: Phones
        public async Task<IActionResult> Index()
        {
            return View(await _context.Phone.ToListAsync());
        }

        public async Task<IActionResult> Search(string name, double price)
        {
            IQueryable<Phone> phones = _context.Phone;

            if (!string.IsNullOrEmpty(name))
                phones = phones.Where(p => p.Name.Contains(name) || p.Company.Contains(name));

            if (price > 0)
                phones = phones.Where(p => p.Price < price);

            return View("Index", await phones.ToListAsync());
        }

        // GET: Phones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // GET: Phones/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Phones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Weight,Id,ProductType,Company,Name,Price,Date,Quantity,Size,img")] Phone phone)
        {
            phone.ProductType = "Phone";
            if (ModelState.IsValid)
            {
                _context.Add(phone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(phone);
        }

        // GET: Phones/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone.FindAsync(id);
            if (phone == null)
            {
                return NotFound();
            }
            return View(phone);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Weight,Id,ProductType,Company,Name,Price,Date,Quantity,Size")] Phone phone)
        {
            if (id != phone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneExists(phone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phone);
        }

        // GET: Phones/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var phone = await _context.Phone.FindAsync(id);
            _context.Phone.Remove(phone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneExists(int id)
        {
            return _context.Phone.Any(e => e.Id == id);
        }
    }
}

ZilZolMarket/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZilZolMarket.Data;
using ZilZolMarket.Models;

namespace ZilZolMarket.Controllers
{
    public class UsersController : Controller
    {
        private readonly ZilZolMarketContext _context;

        public UsersController(ZilZolMarketContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login");
        }


        private async void SignIn(User user)
        {
            //HttpContext.Session.SetString("Type", user.Type.ToString());

            var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.UserName),
                    new Claim("FirstName", user.firstName),
                    new Claim("LastName", user.LastName),
                    new Claim(ClaimTypes.Role, user.UserType.ToString()),
                    new Claim("Id",user.Id.ToString()),
                };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10)
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }

        public bool IsLogin()
        {
            return  (User?.Identity != null && User.Identity.IsAuthenticated);
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Register([Bind("Id,UserName,Password,firstName,LastName,Phone,Email,UserType")] User user)
        {

            // TO DO : Check if username like this is already exists 

            // User with the same email already exists

            user.UserType = UserType.Customer;

            bool ModelError = false;

            if (_context.User.Any(x => x.Email == user.Email))
            {
                ModelState.AddModelError("Email", "User with this email already exists");
                ModelError = true; 


            }

            if (_context.User.Any(x => x.UserName == user.UserName))
            {
                ModelState.AddModelError("UserName", "This User name already exists");
                ModelError = true;

            }

            if (ModelError)
                return View(user);
                

            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                SignIn(user);
                return RedirectToAction(nameof(Index), "Products");
            }
            return RedirectToAction(nameof(Index), "Products");
        }


        [HttpPost]
        public IActionResult Login([Bind("Id,UserName,Password,firstName,LastName,Phone,Email,UserType")] User user)
        {
            var users = _context.User.Where(u => u.UserName == user.UserName && u.Password == user.Password).ToList();

            if (users != null && users.Count() > 0)
            {
                SignIn(users.FirstOrDefault());
                return RedirectToAction(nameof(Index), "Products");
            }

            ModelState.AddModelError("Password", "The user name or password provided is incorrect.");

            return View(user);
        }



        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }


        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            int Id = _context.User.Where(u => u.UserName == HttpContext.User.Identity.Name).FirstOrDefault().Id;

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == Id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

      
        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Password,firstName,LastName,Phone,Email")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
    }
}

ZilZolMarket/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>ZilZolMarket - @ViewData["Title"] </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="~/img/icon2.png">

    <!-- CSS here -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/slicknav.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/slick.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/style.css">


</head>


<body>

    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="~/img/logo/logoZ.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->

    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header ">
                <div class="header-top top-bg d-none d-lg-block">
                    <div class="container-fluid">
                        <div class="col-xl-12">
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="header-info-left d-flex">
                                    <div class="flag">
                                        <img src="/img/icon/Israel.jpg" alt="" style="
                                                                               width: 25px;
                                         ">
                                    </div>
                                    <div style="
                                         color: white;
                                         position: absolute;
                                         left: 32px;
                                         top: 9px;
                                         ">Israel</div>
                                    <ul class="contact-now">
                                        <li style="position: absolute;left: 79px;top: 11px;">+972 50 661 0230</li>
                                    </ul>
                                    <ul class="contact-now" 
                                        style="
                                        position: absolute;
                                        left: 178px;
                                        top: -15px;">
                                        <li class="fb-share-button"
                                             data-href="https://www.ZilZol.co.il/"
                                             data-layout="button_count"
                                             style="padding-top: 15px;">
                                        </li>
                                    </ul>
                                </div>
                                <div class="header-info-right">
                                    <ul>
                                        @{if (User?.Identity != null && User.Identity.IsAuthenticated)
                                            {
                                                <li>

                                                    <a asp-action="Details" asp-controller="Users">My account</a>
                                                </li>
                                                <li><a asp-action="Cart" asp-controller="Products">Cart</a></li>
                                                     
                                                        @if (User.Identity.IsAuthenticated && User.Claims.ElementAt(3).Value == "Admin")
                                                        {
                                                                 <li><a asp-action="Index" asp-controller="Statistics">Statistics</a></li>
                                                        }
                                                                                               <li>
                                            @{ if (User.Identity.IsAuthenticated && User.Claims.ElementAt(3).Value == "Admin")
                                                {

                                                    <a asp-action="Sales" asp-controller="Products">Sales measures</a>
                                                }
                                            }
                                        </li>

                                             }
                                            }
                                                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-1 col-lg-1 col-md-1 col-sm-3">
                                <div class="logo">
                                    <a asp-action="Index" asp-controller="Products"><img src="~/img/logo/logoZ.png" alt=""></a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-8 col-md-7 col-sm-5">
                                <!-- Main-menu -->
                                <div class="main-menu f-right d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a asp-action="Index" asp-controller="Products">Home</a></li>
                                            <li><a asp-controller="Branches" asp-action="Index">Branches</a></li>




                                            <li>
                                                <a href="#">Categories</a>
                                                <ul class="submenu">
                                                    <li><a asp-action="Index" asp-controller="Phones">Phones</a></li>
                                                    <li><a asp-action="Index" asp-controller="Pcs">PC's</a></li>
                                                    <li><a asp-action="Index" asp-controller="Screens">Screens</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-5 col-lg-3 col-md-3 col-sm-3 fix-card">
                                <ul class="header-right f-right d-none d-lg-block d-flex justify-content-between">
                                    <li class="d-none d-xl-block">
                                        <div class="form-box f-right ">
                                            <form asp-action="Search" asp-controller="Products">
                                                <input type="text" name="Name" placeholder="Search products">
                                                <div class="search-icon">
                                                    <i class="fas fa-search special-tag"></i>
                                                </div>
                                            </form>
                                        </div>
                                    </li>
                                    @if (User?.Identity != null && User.Identity.IsAuthenticated)
                                    {
                        <li class="d-none d-lg-block"> <a href="/Users/Logout" class="btn header-btn">Log out</a></li> }
                                    else
                                    {
                        <li class="d-none d-lg-block"> <a href="/Users/Register" class="btn header-btn">Register</a></li>
                                        <li class="d-none d-lg-block"> <a href="/Users/Login" class="btn header-btn">Sign in</a></li>}
                                </ul>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

    <main>
        @RenderBody();


    </main>
    <footer>

        <!-- Footer Start-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo">
                                    <a asp-action="Index" asp-controller="Products"><img src="~/img/logo/logoZ.png" alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>ZilZol Market is the place for you to buy the best electronic devices in a cheap price!</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Products</h4>
                                <ul>
                                    <li><a asp-action="Index" asp-controller="Phones">Phones</a></li>
                                    <li><a asp-action="Index" asp-controller="Pcs">PC's</a></li>
                                    <li><a asp-action="Index" asp-controller="Screens">Screens</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Footer bottom -->
                <div class="row">
                    <div class="col-xl-7 col-lg-7 col-md-7">
                        <div class="footer-copy-right">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->

    </footer>

    <!-- JS here -->
    <!-- All JS Custom Plugins Link Here here -->
    <script src="~/js/vendor/modernizr-3.5.0.min.js"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="~/js/jquery.slicknav.min.js"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/slick.min.js"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/animated.headline.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>

    <!-- contact js -->
    <script src="~/js/contact.js"></script>
    <script src="~/js/jquery.form.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="~/js/plugins.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <!-- Facebook-->
    <script src="~/js/Facebook.js"></script>



    @RenderSection("Scripts", required: false)

</body>
</html>